name: Trigger Fullstack Repo Update

on:
  push:
    branches:
      - main

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update in Fullstack Repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/BasselAlShaar/fullstack-repo/dispatches \
          -d '{"event_type":"update_submodules"}'
